# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c913d3bbffff8d56ee4be9cf421843b91483ef0c570efa0237a8688580cdc90cb660d9edff680232bdebb77d13f58ec80a14068b156ef6d3b13389207ec4b11

test:
  secret_key_base: a86e193d18405d340f08d48115d00c2af75a39cdc0f3dfb615df20791cb70797e4d07a74961928e9d3e242ffe0889f237204c5fbf8db514a4767472f664949f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
